// SPDX-FileCopyrightText: 2021 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2021 Galactic Chimp <63882831+GalacticChimp@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 20kdc <asdd2808@gmail.com>
// SPDX-FileCopyrightText: 2022 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 wrexbe <81056464+wrexbe@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Kara <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2024 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
// SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
// SPDX-FileCopyrightText: 2024 Repo <47093363+Titian3@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Vigers Ray <60344369+VigersRay@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 jmcb <joelsgp@protonmail.com>
// SPDX-FileCopyrightText: 2024 metalgearsloth <comedian_vs_clown@hotmail.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Message;
using Content.Client.Stylesheets;
using Content.Shared.CCVar;
using Content.Shared.Dataset;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Shared.Configuration;
using Robust.Shared.Network;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;
using Robust.Shared.Timing;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using System.Numerics;

namespace Content.Client.Launcher
{
    [GenerateTypedNameReferences]
    public sealed partial class LauncherConnectingGui : Control
    {
        private const float RedialWaitTimeSeconds = 15f;
        private readonly LauncherConnecting _state;
        private float _waitTime;

        // Pressing reconnect will redial instead of simply reconnecting.
        private bool _redial;

        private readonly IRobustRandom _random;
        private readonly IPrototypeManager _prototype;
        private readonly IConfigurationManager _cfg;
        private readonly IClipboardManager _clipboard;

        private readonly IUserInterfaceManager _userInterfaceManager;
        private readonly IUriOpener _uri;
        private readonly IConfigurationManager _configurationManager;
        private readonly ISawmill _sawmill;
        private DefaultWindow? _discordAuthWindow;

        public LauncherConnectingGui(LauncherConnecting state, IRobustRandom random,
            IPrototypeManager prototype, IConfigurationManager config, IClipboardManager clipboard)
        {
            _state = state;
            _random = random;
            _prototype = prototype;
            _cfg = config;
            _clipboard = clipboard;
            // Paradox-Start: Discord auth
            _userInterfaceManager = IoCManager.Resolve<IUserInterfaceManager>();
            _uri = IoCManager.Resolve<IUriOpener>();
            _configurationManager = IoCManager.Resolve<IConfigurationManager>();
            _sawmill = IoCManager.Resolve<ILogManager>().GetSawmill("discord-auth");
            // Paradox-End

            RobustXamlLoader.Load(this);

            LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);

            Stylesheet = IoCManager.Resolve<IStylesheetManager>().SheetSpace;

            ChangeLoginTip();
            RetryButton.OnPressed += ReconnectButtonPressed;
            ReconnectButton.OnPressed += ReconnectButtonPressed;

            CopyButton.OnPressed += CopyButtonPressed;
            CopyButtonDisconnected.OnPressed += CopyButtonDisconnectedPressed;
            ExitButton.OnPressed += _ => _state.Exit();

            var addr = state.Address;
            if (addr != null)
                ConnectingAddress.Text = addr;

            state.PageChanged += OnPageChanged;
            state.ConnectFailReasonChanged += ConnectFailReasonChanged;
            state.ConnectionStateChanged += ConnectionStateChanged;
            state.ConnectFailed += HandleDisconnectReason;

            ConnectionStateChanged(state.ConnectionState);

            // Redial flag setup
            var edim = IoCManager.Resolve<ExtendedDisconnectInformationManager>();
            edim.LastNetDisconnectedArgsChanged += LastNetDisconnectedArgsChanged;
            LastNetDisconnectedArgsChanged(edim.LastNetDisconnectedArgs);
        }

        // Just button, there's only one at once anyways :)
        private void ReconnectButtonPressed(BaseButton.ButtonEventArgs args)
        {
            if (_redial)
            {
                // Redial shouldn't fail, but if it does, try a reconnect (maybe we're being run from debug)
                if (_state.Redial())
                    return;
            }

            _state.RetryConnect();
        }

        private void CopyButtonPressed(BaseButton.ButtonEventArgs args)
        {
            CopyText(ConnectFailReason.Text);
        }

        private void CopyButtonDisconnectedPressed(BaseButton.ButtonEventArgs args)
        {
            CopyText(DisconnectReason.Text);
        }

        private void CopyText(string? text)
        {
            if (!string.IsNullOrEmpty(text))
            {
                _clipboard.SetText(text);
            }
        }

        private void ConnectFailReasonChanged(string? reason)
        {
            // Paradox-Start: Discord auth
            if (reason == null)
            {
                ConnectFailReason.SetMessage("");
                return;
            }

            if (TryParseDiscordAuthDeny(reason, out var code, out var message))
            {
                ShowDiscordAuthDenyWindow(code, message);
                return;
            }
            // Paradox-End

            ConnectFailReason.SetMessage(
                Loc.GetString("connecting-fail-reason", ("reason", reason)));
        }

        // Paradox-Start: Discord auth
        private bool TryParseDiscordAuthDeny(string reason, out string code, out string message)
        {
            code = "";
            message = "";

            if (!reason.Contains("DISCORD_AUTH_DENY|"))
                return false;

            var parts = reason.Split('|', 3);
            if (parts.Length < 3)
                return false;

            code = parts[1]; // НЕ int
            message = parts[2];
            return true;
        }

        private void ShowDiscordAuthDenyWindow(string code, string message)
        {
            Logger.Warning($"DISCORD WINDOW CODE: {code}");

            if (_discordAuthWindow is { Disposed: false })
            {
                _discordAuthWindow.OpenCentered();
                return;
            }
            _sawmill.Warning(_cfg.GetCVar(CCVars.InfoLinksDiscord));
            // Формируем текст через локаль: message = весь текст инструкции + ссылки + код
            var formattedMessage = Loc.GetString(
                "discord-auth-required-text",
                ("inviteUrl", _cfg.GetCVar(CCVars.InfoLinksDiscord)),
                ("channelUrl", _cfg.GetCVar(CCVars.InfoLinksAuthChannelDiscord)),
                ("code", code)
            );

            var vbox = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                SeparationOverride = 15,
                Margin = new Thickness(15)
            };

            var rich = new RichTextLabel();
            rich.SetMarkup(formattedMessage);
            vbox.AddChild(rich);

            var spacer = new Control { MinSize = new Vector2(0, 10) };
            vbox.AddChild(spacer);

            var bottomVBox = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                SeparationOverride = 10,
                HorizontalAlignment = Control.HAlignment.Center
            };

            // Код авторизации
            var codeRow = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                SeparationOverride = 10,
                HorizontalAlignment = Control.HAlignment.Center
            };
            codeRow.AddChild(new Label { Text = Loc.GetString("discord-auth-code-label") });

            var codeLabel = new Label
            {
                Text = code, // обычный текст, без окрашивания
                StyleClasses = { "LabelBig" }
            };
            codeRow.AddChild(codeLabel);
            bottomVBox.AddChild(codeRow);

            // Кнопки
            var copyCodeBtn = new Button { Text = Loc.GetString("discord-auth-copy-code-button") };
            copyCodeBtn.OnPressed += _ =>
            {
                _clipboard.SetText(code);
                // _userInterfaceManager.Popup(Loc.GetString("discord-auth-copy-code-popup"), clipboardButton: false);
            };

            var copyAllBtn = new Button { Text = Loc.GetString("discord-auth-copy-all-button") };
            copyAllBtn.OnPressed += _ =>
            {
                _clipboard.SetText(formattedMessage);
                _userInterfaceManager.Popup(Loc.GetString("discord-auth-copy-all-popup"));
            };

            var channelBtn = new Button { Text = Loc.GetString("discord-auth-open-channel-button") };
            channelBtn.OnPressed += _ => _uri.OpenUri(_cfg.GetCVar(CCVars.InfoLinksAuthChannelDiscord));

            var discordBtn = new Button { Text = Loc.GetString("discord-auth-open-server-button") };
            discordBtn.OnPressed += _ => _uri.OpenUri(_cfg.GetCVar(CCVars.InfoLinksDiscord));

            var closeBtn = new Button { Text = Loc.GetString("discord-auth-close-button") };
            closeBtn.OnPressed += _ => _discordAuthWindow?.Close();

            bottomVBox.AddChild(copyCodeBtn);
            bottomVBox.AddChild(copyAllBtn);
            bottomVBox.AddChild(channelBtn);
            bottomVBox.AddChild(discordBtn);
            bottomVBox.AddChild(closeBtn);

            vbox.AddChild(bottomVBox);

            _discordAuthWindow = new DefaultWindow
            {
                Title = Loc.GetString("discord-auth-window-title"),
                MinSize = new Vector2(880, 600),
                MaxSize = new Vector2(900, 620)
            };

            var footer = new RichTextLabel
            {
                HorizontalAlignment = Control.HAlignment.Center
            };
            footer.SetMarkup(Loc.GetString("discord-auth-footer"));

            vbox.AddChild(new Control { MinSize = new Vector2(0, 10) });
            vbox.AddChild(footer);

            _discordAuthWindow.OnClose += () => _discordAuthWindow = null;
            _discordAuthWindow.Contents.AddChild(vbox);
            _discordAuthWindow.OpenCentered();
        }
        // Paradox-End

        private void LastNetDisconnectedArgsChanged(NetDisconnectedArgs? args)
        {
            HandleDisconnectReason(args);
        }

        private void HandleDisconnectReason(INetStructuredReason? reason)
        {
            if (reason == null)
            {
                _waitTime = 0;
                _redial = false;
            }
            else
            {
                _redial = reason.RedialFlag;

                if (reason.Message.Int32Of("delay") is { } delay)
                {
                    _waitTime = delay;
                }
                else if (_redial)
                {
                    _waitTime = RedialWaitTimeSeconds;
                }

            }
        }

        private void ChangeLoginTip()
        {
            var tipsDataset = _cfg.GetCVar(CCVars.LoginTipsDataset);
            var loginTipsEnabled = _prototype.TryIndex<LocalizedDatasetPrototype>(tipsDataset, out var tips);

            LoginTips.Visible = loginTipsEnabled;
            if (!loginTipsEnabled)
            {
                return;
            }

            var tipList = tips!.Values;

            if (tipList.Count == 0)
                return;

            var randomIndex = _random.Next(tipList.Count);
            var tip = tipList[randomIndex];
            LoginTip.SetMessage(Loc.GetString(tip));

            LoginTipTitle.Text = Loc.GetString("connecting-window-tip", ("numberTip", randomIndex));
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);

            var button = _state.CurrentPage == LauncherConnecting.Page.ConnectFailed
                ? RetryButton
                : ReconnectButton;

            _waitTime -= args.DeltaSeconds;
            if (_waitTime <= 0)
            {
                button.Disabled = false;
                var key = _redial
                    ? "connecting-redial"
                    : _state.CurrentPage == LauncherConnecting.Page.ConnectFailed
                        ? "connecting-reconnect"
                        : "connecting-retry";

                button.Text = Loc.GetString(key);
            }
            else
            {
                button.Disabled = true;
                button.Text = Loc.GetString("connecting-redial-wait", ("time", _waitTime.ToString("00.000")));
            }
        }

        private void OnPageChanged(LauncherConnecting.Page page)
        {
            ConnectingStatus.Visible = page == LauncherConnecting.Page.Connecting;
            ConnectFail.Visible = page == LauncherConnecting.Page.ConnectFailed;
            Disconnected.Visible = page == LauncherConnecting.Page.Disconnected;

            if (page == LauncherConnecting.Page.Disconnected)
                DisconnectReason.Text = _state.LastDisconnectReason;
        }

        private void ConnectionStateChanged(ClientConnectionState state)
        {
            ConnectStatus.Text = Loc.GetString($"connecting-state-{state}");
        }
    }
}
